import React from 'react';
import './About.css';
import Footer from '../Footer';
import Navbar from '../Navbar';

const PrivacyPolicy = () => {
  return (
   <div>
    <Navbar/>
     <div className="privacy-container">
      <h1>Privacy Policy</h1>
      <ol>
        <li>
          <strong>General</strong>
          <ol>
            <li>
              Reliance Retail Limited, having its registered office at 3rd Floor, Court House, Lokmanya Tilak Marg, Dhobi Talao, Mumbai – 400 002, Maharashtra, India (“Reliance”, “we”, “us” or “our”) is managing and operating the websites: WWW.AJIO.COM (“AJIO”), WWW.LUXE.AJIO.COM (“AJIO Luxe”) and the mobile application thereof (AJIO and AJIO Luxe are collectively referred to as the “Platforms”) through which Reliance inter alia facilitates the sale and purchase of a diverse range of fashion, home, lifestyle and other products and services listed on and sold on the Platforms from time to time (“Products”) to the users of the Platforms (“User” or “Users” or “you” or “your”). The term User/User(s) means any individual or entity which uses, accesses or browses the Platform and/or purchases Products from the Platform.
            </li>
            <li>
              Reliance is committed to protecting and respecting your privacy. This privacy policy (“Privacy Policy”), together with the AJIO and AJIO LUXE TERMS AND CONDITIONS (“Terms of Use”) and all other policies notified by us from time to time governs your use of the Platforms. This Privacy Policy describes our policies and procedures on the collection, use, disclosure, sharing, processing, transfer, storage, retention and safeguarding of the Information (defined hereinafter) provided to us by you through the use of the Platforms and/or pursuant to the purchase of the Products on the Platforms.
            </li>
          </ol>
        </li>
        <li>
          <strong>Applicability of the Privacy Policy</strong>
          <ol>
            <li>
              By using, browsing, accessing, or purchasing Products from the Platforms and/or by submission of Information (and in case of a minor - submission of such minor’s Information either by the parents or the legal guardian), you agree to be bound by the terms of this Privacy Policy and consent to the collection, use, storage, possession, dealing, processing, handling, sharing, disclosure, transfer or retention of your Information in accordance with the terms of the Privacy Policy and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. We shall not use the User’s Information in any manner except as provided under this Privacy Policy and to the extent permitted under the laws applicable to data protection and privacy. All capitalized terms used herein if not defined shall have the same meaning as ascribed to them under the Terms of Use.
            </li>
            <li>
              You may be able to access or browse the Platforms from outside the geographical territories of the Republic of India, however please note that the Products listed on the Platform and not offered for sale outside the geographical territories of the Republic of India. Your Information will primarily be collected, stored and processed in India and will be governed by the applicable laws (including data protection and privacy laws) that are different from those that apply in the country in which you are located.
            </li>
            <li>
              This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made thereunder as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </li>
            <li>
              You may be asked to provide your information anytime you visit, access, use or browse the Platforms. We may share information and use it consistent with the provisions of this Privacy Policy. We may also combine it with other information to provide and improve our Products, services, content and advertising. Please take a moment to familiarize yourself with our Privacy Policy. If you do not agree with any provisions of the Terms or this Privacy Policy, we advise you to not use or access the Platforms.
            </li>
          </ol>
        </li>
        <li>
          <strong>Type of Information Collected</strong>
          <ol>
            <li>
              This Privacy Policy sets out the type of Information collected from the Users, including the nature of the Sensitive Personal Data/ Information (defined hereinafter), the purpose, means and modes of usage of such Information and how and to whom we shall disclose, share or transfer such Information. You may at any time withdraw your consent for collection and use of your Information including Personal Information (defined hereinafter) or Sensitive Personal Data/ Information. However, please note that if you withdraw your consent, we may no longer be able to provide you with the corresponding service for which you have withdrawn your consent. It is hereby clarified that your decision to withdraw your consent will not affect the processing of Information based on your previous consent prior to the withdrawal.
            </li>
            <li>
              We may collect a variety of Information from you, including your name, mailing address, phone number, email address and contact preferences, including any other usage and interaction details with us or our affiliates. We may collect such information which when combined with other pieces of information available with us could reasonably allow you to be identified (“Personal Information”). Personal Information shall include but is not limited to your full name, personal contact numbers, residential address, email address, gender, date of birth. Personal Information can be in any format including but not limited to photographs or documents.
            </li>
            <li>
              We may also collect such Non-Personal Information which when clubbed with Personal Information shall be treated as Personal Information. Non-Personal Information includes data or information that doesn’t personally identify you and may include hardware identifiers, unique systems or application software etc.
            </li>
            <li>
              We may also collect, receive, process or store certain sensitive personal data/ information provided by you which may consist of, but not be limited to:
              <ol>
                <li>Password;</li>
                <li>Financial information such as bank account or credit card or debit card or other payment instrument details;</li>
                <li>Any detail relating to (a) and (b) above as provided to us for providing the Products and/or processing your orders placed with us on the Platform; and</li>
                <li>Any of the information received under (a) and (b) above by us for processing or storing under lawful contract or otherwise.</li>
              </ol>
              (Collectively, referred to as “Sensitive Personal Data/ Information”).
              Personal Information and Sensitive Personal Data/Information are collectively referred to as “Information”.
            </li>
            <li>
              You agree to provide information, which shall be true, correct, up to date and accurate. You may access, amend, alter or require deletion of your information partially or fully by contacting us at customercare@ajio.com.
            </li>
            <li>
              The Platforms are not directed towards minors. We do not knowingly collect Personal Information from any User who is under 18 (Eighteen) years. If we are made aware that we have collected the Personal Information of a person below the age of 18 (Eighteen) years, we will take steps to delete the Information within a reasonable time frame. If a parent or legal guardian becomes aware that his or her child has provided his/ her Information on the Platforms without their consent, he or she shall contact us for the deletion of such Information. In the event, where in contravention to the Privacy Policy and Terms of Use, a person below the age of 18 (Eighteen) uses the services, we shall not be held liable or responsible for any damage or injury suffered by such person.
            </li>
            <li>
              Location Information: We may also collect information related to your location through Bluetooth and Wifi signals or other technologies. In order to collect geo-location information, the location settings must be enabled on your Device. Therefore, in some cases, the Platform may request that you enable the location settings. Except in cases where any specific services requested by you require or involve personal identification, the Platform collects location data anonymously and in a form that does not personally identify you.
            </li>
            <li>
              Other Information: The Platform also may collect other information about you in ways that the Platform describes to you or otherwise with your consent like the permission to access your location, camera usage microphone access etc. You can choose not to provide us with certain types of information, but doing so may affect your ability to avail and/or use some services on the Platform.
            </li>
          </ol>
        </li>
        <li>
          <strong>Use of Information Collected</strong>
          <ol>
            <li>
              We may collect Information, whenever relevant, to help provide you with information and to complete or process any transaction or display any Product you have requested or to participate in any online event or contest. You also consent to the collection of certain Information or document as per the applicable laws in the course of your purchasing the Products on the Platform.
            </li>
            <li>
              We may collect, use or process your information including Personal Information and Sensitive Personal Data/ Information for the following purposes:
              <ol>
                <li>For creating and giving you access to your registered account on the Platforms.</li>
                <li>To validate and process your request for the provision of Products or accessing of the Platforms.</li>
                <li>To assist merchants to handle and fulfil your orders.</li>
                <li>To develop, deliver, process and improve our Products, services, content in order to personalize and improve your experience.</li>
                <li>To inform you about our Products and/or third-party products, services, offers, discounts, updates, promotional initiatives, upcoming events, that may be of your interest, including providing you information in relation to your order confirmations, invoices, delivery status, technical notices, security alerts, etc.</li>
                <li>For our internal business analytical and research purposes such as auditing, data analysis and research to improve our Products, services and customer communications.</li>
                <li>To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.</li>
                <li>To provide you with recommendation about Products you may be interested in, based on your use of the Platforms or browsing behavior.</li>
                <li>To provide you with marketing communications and advertising that we believe may be of interest for you;</li>
                <li>To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Platforms.</li>
                <li>To detect or monitor any fraudulent or illegal activity on the Platforms.</li>
                <li>To facilitate software updates, product support, improve the Platform experience and services therein and to verify compliance with the terms of this Policy.</li>
              </ol>
            </li>
            <li>
              When you use our voice, image and camera services, we use your voice input, images, videos, and other Information to respond to your requests, provide the requested Products to you, and improve our services or the Platform.
            </li>
            <li>
              The Platform transmits, collects, maintains, processes and use the location data and information to provide and improve the design, functionality, performance, and content of the Platform.
            </li>
          </ol>
        </li>
      </ol>
    </div>
    <Footer/>
   </div>
  );
}

export default PrivacyPolicy;
